# Generated by Django 3.1.7 on 2021-04-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
