# Generated by Django 3.1.7 on 2021-03-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
