# Generated by Django 3.1.7 on 2021-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_commenter_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_profile',
            new_name='commenter_profile_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_profile_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
