# Generated by Django 3.1.7 on 2021-03-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210320_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_profile_id',
            new_name='commenter_profile',
        ),
    ]
