# Generated by Django 3.1.7 on 2021-03-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
